name: Deploy To Firebase
author: Lallu Anthoor <lalluanthoor@gmail.com>
description: A GitHub Action to deploy to Firebase
inputs:
  params:
    description: Additional parameters for firebase command
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'upload-cloud'
  color: 'blue'
